# Usamos una versión ligera de Python 3.12 como base
FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .

# Instalamos esas librerías sin guardar basura temporal
RUN pip install --no-cache-dir -r requirements.txt

# Copiamos nuestra carpeta de código al contenedor
COPY ./app ./app

# Avisamos que la aplicación usará el puerto 5010
EXPOSE 5010

# Comando para arrancar el servidor usando uvicorn dándole la ruta del archivo y puerto
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "5010"]