FROM python:3.12-slim

#queremos usar nuestro contenedor de docker 

#definimos nuestra propia imagen en este caso docker file

#entre mas pequenos los contenedores mejor para no tener un mayor consumo de memoria 

#Creamos carpeta de trabajo del contenedor
WORKDIR /app

#copiamos los requerimentos del servidor
COPY requirements.txt . 
#con el punto le decimos que del lado del contenedor cree un archivo igual 

#instlamos los requerimentos
RUN pip install --no-cache-dir -r requirements.txt

#copiar el codigo del API
COPY ./app ./app

#exponer el puerto con el cual trabajara el servidor
# se hace una reserva de puertos 
#le decimos que queremos trabjar en el 8000

EXPOSE 8000

#comando de ejecucion FASTAPI
#espesificar el comando para ejecutar el servidor de fastapi
#pasamos los palametros en este caso 
#uvirocn es el servidor de fastapi
#app.main:app es la ruta del archivo y la instancia del servidor
#--host es para decirle a que ip se va a conectar el servidor en este caso
#--port es para decirle a que puerto se va a conectar el servidor en este caso el 5000
#--reload es para que el servidor se reinicie cada vez que hagamos un cambio en el codigo
CMD ["uvicorn","app.main:app","--host","0.0.0.0","--port","8000","--reload"]