#Importamos la imagen de python 3.12 slim
FROM python:3.12-slim

#Creamos la carpeta de trabajo del contenedor
WORKDIR /app

#Copiamos el archivo de requerimientos del servidor
COPY requirements.txt .

#Instalamos los requerimientos
RUN pip install --no-cache-dir -r requirements.txt

#Copiar el código de la API
COPY ./app ./app

#Exponer el puerto
EXPOSE 5000

#Comando de ejecución FASTAPI
#CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]
CMD ["uvicorn", "app.biblioteca:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]