# Usamos una versión de python ligera para que el contenedor no pese tanto
FROM python:3.12-slim

# Creamos una carpeta llamada app dentro de docker para meter nuestro código
WORKDIR /app

# Copiamos la lista de librerías necesarias al contenedor
COPY requirements.txt .

# Ejecutamos la instalación de las librerías sin guardar archivos temporales innecesarios
RUN pip install --no-cache-dir -r requirements.txt

# Copiamos nuestra carpeta donde está el código de python al contenedor
COPY ./app ./app

# Exponemos el puerto 8080 que es donde va a correr nuestra aplicación
EXPOSE 8080

# El comando final para arrancar nuestra api usando uvicorn dándole el puerto y el host
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]